### ISSUE TITLE
Lazy-loading-routes vs AsyncRoute in Angular2 Beta

### ISSUE THREAD

**Issue by PrimeObjects** [mgechev/lazy-loading-routes-angular2#2]
Hi Minko,

The document to angular2 beta is not finished and I still have no idea how the official lazy loading route will work (I mean that comes from angular2/router'. Will your solution be replaced and therefore obsolete by the official AsyncRouter?

Thanks lot
Gary

**Comment by mgechev** [comment]
You can use both - virtual proxy or the official AsyncRoute, depending on your use case :-).
